### ISSUE TITLE
File cannot be opened directly from Aria2app

### ISSUE THREAD

**Issue by sudo-why** [devgianlu/Aria2App#183]
The button to directly open files doesn't work properly. Clicking it shows "no app found" even for common file types like pdf and docx.

OS: Android 8.0 with EMUI 8.

**Comment by devgianlu** [comment]
Where are you trying to do this? You can also provide a screenshot

**Comment by sudo-why** [comment]
I was talking about this button. 
![IMG_20210619_120328](https://user-images.githubusercontent.com/86039108/122634076-ca09b500-d0f9-11eb-966b-b731ad59cbe2.jpg)

Pressing it shows no app found but I can open these files from other apps. 
![IMG_20210619_120758](https://user-images.githubusercontent.com/86039108/122634073-c7a75b00-d0f9-11eb-88b0-a69335390301.jpg)

**Comment by sudo-why** [comment]
Thanks! Any idea when the new version will be available in play store?

**Comment by devgianlu** [comment]
> Thanks! Any idea when the new version will be available in play store?

I've published yesterday, but Google is still processing it. Hopefully in the next 8 hours.

**Comment by sudo-why** [comment]
I just installed the latest update from play store, but the problem still remains. Same error is shown.

**Comment by devgianlu** [comment]
https://github.com/devgianlu/Aria2App/commit/15249e8c0fed1b9d9afed72e15fac2202b353410
